### ISSUE TITLE
Feedback from Supervisor：Daily Report Failed

### ISSUE THREAD

**Issue by dukechain2333** [cloudy-sfu/SLU-Daily-Report#2]
I have tried couples of times today. The daily-report system told me that I have already reported. But I got feedback from my supervisor, saying she couldn't find me in the list.

**Supervisor's feedback suggest that neither did user's report appear in the non-report list nor the reported list.**

**Comment by cloudy-sfu** [comment]
It is most likely the problem related to class ID or school ID, because the tests on the student in a same class are all passed.
@dukechain2333

**Comment by dukechain2333** [comment]
Issue solved

The issue is mainly due to multi report in one account. The daily report system only allows users to fill in only once a day.

Thank you @cloudy-sfu .
